
version: 2

models:
  - name: dim_date
    description: "date dimension"  
    columns:
      - name: date_key
        description: date key
        tests:
          - unique
          - not_null   
  - name: dim_course
    description: "course dimension"
    columns:
      - name: course_key
        description: course key
        tests:
          - unique
          - not_null
      - name: course_code
        description: course code
      - name: course_title
        description: course title

  - name: dim_student
    description: "student dimension"
    columns:
      - name: student_key
        description:  student key
        tests:
          - unique
          - not_null
      - name: first_name
        description: first name
      - name: last_name
        description: last name
      - name: email
        description: email

  - name: dim_unit
    description: "unit dimension"
    columns:
      - name: unit_key
        description:  unit key
        tests:
          - unique
          - not_null
      - name: unit_code
        description: unit code
      - name: unit_title
        description: unit title
      - name: unit_credit_point
        description: unit credit point

  - name: fact_student_unit_enrolment
    description: "student unit enrolment fact table"
    columns:
      - name: student_unit_enrolment_key
        description: Primary key of the table
        tests:
          - unique
          - not_null
      - name: unit_key
        description: foreign key for unit
        tests:
          - relationships:
              to: ref('dim_unit')
              field: unit_key
      - name: course_key
        description: foreign key for course
        test:
          - relationships:
              to: ref('dim_course')
              field: course_key
      - name: student_key
        description: foreign key for student
        test:
          - relationships:
              to: ref('dim_student')
              field: student_key
      - name: course_admission_key
        description: foreign key for course admission
        test:
          - relationships:
              to: ref('dim_course_admission')
              field: course_admission_key
      - name: enrolment_date_key
        description: foreign key for date
        test:
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: enrolment_status
        description: "{{ doc('StatusEnrolment') }}"
      - name: fee_amount
        description: fee amount

  - name: dim_course_admission
    description: "course admission dimension"
    columns:
      - name: course_admission_key
        description: course admission key
        tests:
          - unique
          - not_null
      - name: course_admission_status
        description: "{{ doc('StatusCourseAdmission') }}"
      - name: status_effective_date_key
        description: status effective date key
